<?php if(!defined("__JGWEDDING__")) die("No Access");
	
	$_PAGE["title"] = "Home";
?>
<h3>Our Story</h3>
<div>
	<img src="<?php echo IMG_DIR; ?>Grad_BW.png" style="float:right; width:500px; padding-left: 20px; padding-bottom: 20px;" />
	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur vel pretium turpis. Vivamus bibendum mi ut nisi semper, eget mattis nunc placerat. Donec ultrices libero et tempor varius. Nulla at quam risus. Ut ac libero quis nisl laoreet sodales vulputate eget erat. Fusce nec dolor tristique, volutpat orci sed, sodales arcu. Mauris auctor imperdiet mauris et hendrerit. Mauris consequat ante a est hendrerit, eu imperdiet nisi pulvinar.</p>
	<p>Cras justo neque, eleifend eget mollis sit amet, egestas a neque. Nullam ac laoreet tortor, vel viverra purus. Mauris placerat lobortis ipsum eu semper. Sed congue orci id pretium ullamcorper. Duis quis pharetra metus. Cras viverra nibh quis ligula sodales, ut luctus augue lobortis. Proin accumsan augue vel hendrerit convallis. Quisque at ligula eget ipsum lacinia tempus ultrices et diam. Fusce varius venenatis erat eget mollis. Aliquam a tempus augue. Sed dictum dapibus velit eu semper. Duis vehicula enim vel libero ornare posuere. Nulla a dictum arcu. Curabitur sapien sapien, consectetur lobortis lectus nec, blandit varius est. Nulla nec turpis vulputate, viverra sapien in, tempus magna. Curabitur facilisis ex nec nibh dictum, blandit vestibulum ex egestas.</p>
	<p>Morbi imperdiet auctor arcu vel dapibus. Praesent nunc mauris, pretium at orci vitae, cursus pharetra tellus. Nullam vel finibus urna, non laoreet mauris. Aenean vel aliquet nisi, et gravida neque. Etiam lacinia ex ut felis iaculis pulvinar. Aenean at condimentum orci, non venenatis lectus. Nunc facilisis rhoncus pharetra. Etiam sapien mi, pharetra in turpis eget, tempor lobortis felis. Sed iaculis tortor eu leo tempus, a pretium nulla pretium. Quisque rutrum risus id dolor tincidunt, at pharetra eros convallis. Praesent ac luctus risus, id scelerisque purus. Proin luctus auctor blandit. Vivamus eu urna eleifend nunc vestibulum sollicitudin. Fusce in posuere est, nec pretium erat. Etiam quis eros quis sapien semper sagittis elementum a leo. Vivamus non convallis purus.</p>
</div>